package com.mas.jacketcoach;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;

import android.annotation.SuppressLint;
import android.app.DatePickerDialog;
import android.content.DialogInterface;
import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.DatePicker;
import android.widget.EditText;
import android.widget.Toast;

import com.google.android.gms.maps.MapFragment;
import com.google.android.gms.maps.model.LatLng;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.mas.jacketcoach.helper.MapStateManager;
import com.mas.jacketcoach.helper.Validator;
import com.mas.jacketcoach.model.Event;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;


public class AddEventActivity extends AppCompatActivity {

    private EditText nameEditText;
    private EditText sportEditText;
    private EditText date_field;
    private LatLng latlng;
    private DatabaseReference mDatabase;
    private FirebaseUser user;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_add_event);

        //Initialize top bar
        Toolbar myToolbar = (Toolbar) findViewById(R.id.main_toolbar);
        setSupportActionBar(myToolbar);

        //Retrieve values from MapsFragment
        latlng = getIntent().getExtras().getParcelable("LAT_LNG");

        // Initialize UI elements
        nameEditText = (EditText) findViewById(R.id.name);
        sportEditText = (EditText) findViewById(R.id.sport);
        date_field = (EditText)findViewById(R.id.date);
        date_field.setFocusable(false); // disable editing of this field
        date_field.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(final View v) {
                chooseDate();
            }
        });

        //Firebase setup
        mDatabase = FirebaseDatabase.getInstance().getReference();
        FirebaseUser user = FirebaseAuth.getInstance().getCurrentUser();
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        return true;
    }

    // ToolBar actions
    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case R.id.action_settings:
                // User chose the "Settings" item, show the app settings UI...
                Log.d("NAVIGATION","setting");
                return true;

            default:
                // If we got here, the user's action was not recognized.
                // Invoke the superclass to handle it.
                return super.onOptionsItemSelected(item);

        }
    }

    @Override
    public void onStart() {
        super.onStart();
        // Check if user is signed in (non-null) and update UI accordingly.
        user = FirebaseAuth.getInstance().getCurrentUser();
        if (user != null){
            // reload();
        }
    }

    public void addEvent(View view) {
        //Parsing input
        String enteredName = nameEditText.getText().toString();
        String enteredSport = sportEditText.getText().toString();
        String enteredDate = date_field.getText().toString();

        //Validating input
        if (!Validator.isValidText(enteredName)) {
            nameEditText.setError("Invalid Name Entered");
            return;
        }
        if (!Validator.isValidText(enteredSport)) {
            sportEditText.setError("Invalid Sport Entered");
            return;
        }
        DateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        sdf.setLenient(false);
        try { sdf.parse(enteredDate); }
        catch ( Exception e ) { date_field.setError("Invalid Date"); }

        //Pushing input
        DatabaseReference newRef = mDatabase.child("events").push();
        Date currentTime = Calendar.getInstance().getTime();
        //I don't think we need an id field because the event key generated by push() identifies the event. So its a constant 1.
        ArrayList<String> players = new ArrayList<String>();
        players.add(user.getUid());

        Event event = new Event(1, user.getUid(), enteredName, enteredSport, enteredDate, latlng.latitude, latlng.longitude, players);
        newRef.setValue(event);
        Toast.makeText(getApplicationContext(), "Event Created!", Toast.LENGTH_SHORT);
        MapStateManager mapStateManager = new MapStateManager(this.getApplicationContext());
        mapStateManager.centerOnEvent((float) latlng.latitude,(float) latlng.longitude);
        Intent intent = new Intent(AddEventActivity.this, MainActivity.class);
        startActivity(intent);
    }

    private void chooseDate() {
        final Calendar calendar = Calendar.getInstance();
        final int year = calendar.get(Calendar.YEAR);
        final int month = calendar.get(Calendar.MONTH);
        final int day = calendar.get(Calendar.DAY_OF_MONTH);
        DatePickerDialog datePicker =
                new DatePickerDialog(this, new DatePickerDialog.OnDateSetListener() {
                    @Override
                    public void onDateSet(final DatePicker view, final int year, final int month,
                                          final int dayOfMonth) {

                        @SuppressLint("SimpleDateFormat")
                        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                        calendar.set(year, month, dayOfMonth);
                        String dateString = sdf.format(calendar.getTime());

                        date_field.setText(dateString); // set the date
                    }
                }, year, month, day); // set date picker to current date

        datePicker.show();

        datePicker.setOnCancelListener(new DialogInterface.OnCancelListener() {
            @Override
            public void onCancel(final DialogInterface dialog) {
                dialog.dismiss();
            }
        });
    }
}